In [53]:
# Python notes: Class 4

# Install a library (module)
# Open anaconda prompt -> conda install numpy (not necessary if it's already installed)

# Import numpy, and rename it as np so it can be referenced more easily
import numpy as np
import pandas as pd

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
# Call the array method from the np library to convert the list to a numpy array
# This lets you use built-in methods from numpy on the list
np.array(my_list)

array([1, 2, 3])

In [4]:
# Create a matrix by nesting lists
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
# Convert the matrix to a np array

np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
# The arrange method

# Two arguments (start, stop)
np.arange(0, 10)

# Three arguments (step size)
np.arange(0, 10, 2)



array([0, 2, 4, 6, 8])

In [7]:
# A placeholder matrix filled completely with zeros

# 5x5
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
# Matrix filled with ones...

#5x5
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
# Linear spacing of n values in a range

np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [10]:
# Create a matrix of 50 numbers spaced evenly from one to ten

np.linspace(0, 10, 50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [11]:
# Identity matrices
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
# Random value generation

# Random has its own methods

# Two numbers from a uniform distribution
np.random.rand(2)

# A random matrix from the uniform distribution
np.random.rand(5,5)

# From a standard normal distribution
np.random.randn(5,5)

# Random integers (start, stop, n)
np.random.randint(1, 101, 10)


array([ 9, 70, 52, 40, 56, 70,  3, 62, 73, 75])

In [13]:
# Make some arrays
arr = np.arange(25)
ranarr = np.random.randint(0, 50, 10)

arr
ranarr

array([ 3, 20, 25, 34, 11,  0, 18, 39,  4,  0])

In [14]:
# Reshape arrays

# Call rashape rirectly on the array
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [15]:
# The maximum, minimum, etc.
ranarr.max()

39

In [16]:
ranarr.argmax() # The position of the maximum value in ranarr

7

In [17]:
ranarr.min()

0

In [18]:
ranarr.argmin()

5

In [19]:
# Matrix dimensions (after reshaping it)
arr = arr.reshape(5,5)
arr.shape

(5, 5)

In [20]:
# Create a matrix
np.mat(arr)

matrix([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])

In [21]:
# The type of this matrix (return the dtype attribute)
arr.dtype

dtype('int32')

In [22]:
# Indexing and slicing matrices
arr = np.arange(25)

In [23]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
# The 9th element
arr[8]

8

In [25]:
# Ranges
arr[1:5]

array([1, 2, 3, 4])

In [26]:
# Broadcasting... (resetting values)
arr[0:5] = 100 # change the first 5 values of arr to 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [27]:
# Reset array
arr = np.arange(25)

# Slice of arr
slice_arr = arr[0:6]
slice_arr

array([0, 1, 2, 3, 4, 5])

In [28]:
slice_arr[:] = 99 # Set all values of slice_arr to 99

In [29]:
arr # The broadcasting function gets applied to the original array too

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [30]:
arr_copy = arr[0:6].copy() # copy an array if you don't want changes to a subset to be reflected in the original
arr_copy

array([99, 99, 99, 99, 99, 99])

In [31]:
arr2d = np.array(([5,10,15], [20, 25, 30], [35,40,45])) #2d array
arr2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [32]:
np.arange(5, 46, 5).reshape(3,3) # A better way to create the same matrix using the reshape function

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [33]:
# Matrix indexing

arr2d[0] # the first row 

array([ 5, 10, 15])

In [34]:
# In general, indexing works as array[row, column] or array[row][column]
arr2d[1, 0] # Scond row, first column

20

In [35]:
# Matrix slicing
arr2d[:2, :2] # Give every row up until the third, and every column up to the third

array([[ 5, 10],
       [20, 25]])

In [36]:
# Just the last column
arr2d[:,2]

array([15, 30, 45])

In [37]:
# create a large matrix
arr2d = np.arange(1,101).reshape(10,10)
arr2d

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [38]:
arr2d[[0, 2, 4, 6, 8,]] # grab these rows

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
       [81, 82, 83, 84, 85, 86, 87, 88, 89, 90]])

In [39]:
arr2d[[1, 7, 3, 2, 8,]] # In any order you want

array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [71, 72, 73, 74, 75, 76, 77, 78, 79, 80],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [81, 82, 83, 84, 85, 86, 87, 88, 89, 90]])

In [40]:
arr2d[:,[1, 2, 3, 4]] # Select columns

array([[ 2,  3,  4,  5],
       [12, 13, 14, 15],
       [22, 23, 24, 25],
       [32, 33, 34, 35],
       [42, 43, 44, 45],
       [52, 53, 54, 55],
       [62, 63, 64, 65],
       [72, 73, 74, 75],
       [82, 83, 84, 85],
       [92, 93, 94, 95]])

In [41]:
# Diagonal elements
arr2d[[0,1,2,3,4,5,6,7,8,9], [0,1,2,3,4,5,6,7,8,9]]

array([  1,  12,  23,  34,  45,  56,  67,  78,  89, 100])

In [42]:
# Some operators
arr2d > 30

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [43]:
arr2d * arr2d # element by element multiplication

array([[    1,     4,     9,    16,    25,    36,    49,    64,    81,
          100],
       [  121,   144,   169,   196,   225,   256,   289,   324,   361,
          400],
       [  441,   484,   529,   576,   625,   676,   729,   784,   841,
          900],
       [  961,  1024,  1089,  1156,  1225,  1296,  1369,  1444,  1521,
         1600],
       [ 1681,  1764,  1849,  1936,  2025,  2116,  2209,  2304,  2401,
         2500],
       [ 2601,  2704,  2809,  2916,  3025,  3136,  3249,  3364,  3481,
         3600],
       [ 3721,  3844,  3969,  4096,  4225,  4356,  4489,  4624,  4761,
         4900],
       [ 5041,  5184,  5329,  5476,  5625,  5776,  5929,  6084,  6241,
         6400],
       [ 6561,  6724,  6889,  7056,  7225,  7396,  7569,  7744,  7921,
         8100],
       [ 8281,  8464,  8649,  8836,  9025,  9216,  9409,  9604,  9801,
        10000]])

In [44]:
np.max(arr2d) # maximum values

100

In [45]:
np.log(arr2d)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
        1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509],
       [2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
        2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227],
       [3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582,
        3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738],
       [3.4339872 , 3.4657359 , 3.49650756, 3.52636052, 3.55534806,
        3.58351894, 3.61091791, 3.63758616, 3.66356165, 3.68887945],
       [3.71357207, 3.73766962, 3.76120012, 3.78418963, 3.80666249,
        3.8286414 , 3.8501476 , 3.87120101, 3.8918203 , 3.91202301],
       [3.93182563, 3.95124372, 3.97029191, 3.98898405, 4.00733319,
        4.02535169, 4.04305127, 4.06044301, 4.07753744, 4.09434456],
       [4.11087386, 4.12713439, 4.14313473, 4.15888308, 4.17438727,
        4.18965474, 4.20469262, 4.21950771, 4.2341065 , 4.24849524],
       [4.26267988, 4.27666612, 4.2904594

In [46]:
A = np.arange(1,5).reshape(2,2)

In [47]:
A*A

array([[ 1,  4],
       [ 9, 16]])

In [48]:
a = np.mat(A)

In [49]:
a*a # Actual matrix multiplication

matrix([[ 7, 10],
        [15, 22]])

In [50]:
a.T # Transpose

matrix([[1, 3],
        [2, 4]])

In [54]:
# Handling missing data
df = pd.DataFrame({'A': [1, 2, np.nan], 'B' : [5, np.nan, np.nan], 'C' : [1,2,3]})

In [55]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [57]:
# Drop all rows that have missing values
df.dropna()

A    B  C
0  1.0  5.0  1

In [58]:
# Drop is the column has any nas
df.dropna(axis = 1)

C
0  1
1  2
2  3

In [59]:
# Drop if row has > n nas
df.dropna(thresh = 2)

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [60]:
# Recode nas
df.fillna(value = 'Missing')

A        B  C
0        1        5  1
1        2  Missing  2
2  Missing  Missing  3

In [63]:
# Fill in missing values of a specific column with some value
df['A'].fillna(value = df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

### Groupby
 df.groupby method. The idea is to perform calculations on groups defined by some variable in your dataset (like the 'group_by' function from dplyr)

Grouped dataframes can be assigned back to their own objects. 

NewObj = df.groupby

Then, other methods can be called on the grouped object. E.g. NewObj.mean() to perform group-wise means.

Another nice option is the .describe method (similar to summary function from R)

NewObj.describe()

### Merging, Joining and concatenation

In [67]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[4, 5, 6, 7]) 
df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                        index=[8, 9, 10, 11])

In [68]:
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [69]:
df2

A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [70]:
df3

A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [71]:
# pd.concat for concatenaton, no keys used, not a merge. Think rbind or cbind

pd.concat([df1, df2, df3])

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [72]:
pd.concat([df1, df2, df3], axis = 1)

A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

In [89]:
# Merging
left = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})
   
right = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                          'C': ['C0', 'C1', 'C2', 'C3'],
                          'D': ['D0', 'D1', 'D2', 'D3']})

In [90]:
left

key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3

In [91]:
right

key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2
3  K3  C3  D3

In [92]:
# Merge (df1, df2, how (left, right, inner, outer), on = variable to merge on)
pd.merge(left, right, how='inner', on='key')

key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

In [93]:
left = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3']})
    
right = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                               'key2': ['K0', 'K0', 'K0', 'K0'],
                                  'C': ['C0', 'C1', 'C2', 'C3'],
                                  'D': ['D0', 'D1', 'D2', 'D3']})

In [94]:
left

key1 key2   A   B
0   K0   K0  A0  B0
1   K0   K1  A1  B1
2   K1   K0  A2  B2
3   K2   K1  A3  B3

In [95]:
right

key1 key2   C   D
0   K0   K0  C0  D0
1   K1   K0  C1  D1
2   K1   K0  C2  D2
3   K2   K0  C3  D3

In [96]:
## Merge using two keys. By default, this will perform an inner join
pd.merge(left, right, on=['key1','key2'])

key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

In [97]:
# You can still perform different kinds of joins using the how argument
pd.merge(left, right, on=['key1','key2'], how = 'outer') # outer join

key1 key2    A    B    C    D
0   K0   K0   A0   B0   C0   D0
1   K0   K1   A1   B1  NaN  NaN
2   K1   K0   A2   B2   C1   D1
3   K1   K0   A2   B2   C2   D2
4   K2   K1   A3   B3  NaN  NaN
5   K2   K0  NaN  NaN   C3   D3

In [98]:
left = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                     'B': ['B0', 'B1', 'B2']},
                      index=['K0', 'K1', 'K2']) 

right = pd.DataFrame({'C': ['C0', 'C2', 'C3'],
                    'D': ['D0', 'D2', 'D3']},
                      index=['K0', 'K2', 'K3'])

In [99]:
left

A   B
K0  A0  B0
K1  A1  B1
K2  A2  B2

In [100]:
right

C   D
K0  C0  D0
K2  C2  D2
K3  C3  D3

In [101]:
# Joins with predefined indices are straightforward
left.join(right)

A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

In [102]:
# You can still perfom different joins
left.join(right, how = 'outer')

A    B    C    D
K0   A0   B0   C0   D0
K1   A1   B1  NaN  NaN
K2   A2   B2   C2   D2
K3  NaN  NaN   C3   D3

In [103]:
# Some pandas operations

# Define a new dataframe
df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})

In [104]:
# Last n rows
df.tail(2)

col1  col2 col3
2     3   666  ghi
3     4   444  xyz

In [106]:
# unique rows
df['col2'].unique()

array([444, 555, 666], dtype=int64)

In [107]:
# Number of unique values
df['col2'].nunique()

3

In [108]:
# Table of counts for a variable
df['col2'].value_counts()

444    2
555    1
666    1
Name: col2, dtype: int64

In [109]:
# Permanantly delete a column
del df['col1']

In [110]:
df

col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

In [111]:
# Column names
df.columns # an attribute of the dataframe

Index(['col2', 'col3'], dtype='object')

In [112]:
# Sort based on a column
df.sort_values(by = 'col3') # not permanant

col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

In [113]:
df.sort_values(by = 'col3', inplace = True) # permanant

In [114]:
df

col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

In [115]:
# find missing values
df.isnull()

col2   col3
0  False  False
1  False  False
2  False  False
3  False  False

In [118]:
# drop nas
df.dropna()

col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

In [121]:
# pivot table
data = {'A':['foo','foo','foo','bar','bar','bar'],
     'B':['one','one','two','two','one','one'],
       'C':['x','y','x','y','x','y'],
       'D':[1,3,2,5,4,1]}
df = pd.DataFrame(data)
df

A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

In [122]:
df.pivot_table(values = 'D', index = ['A', 'B'], columns = 'C')

C          x    y
A   B            
bar one  4.0  1.0
    two  NaN  5.0
foo one  1.0  3.0
    two  2.0  NaN