In [1]:
# Create two vectors (A and B), where A is (1,2,3) and B is (4,5,6). With these vectors, use the cbind() or rbind() function to create a 2 x 3 matrix from the vectors. Based on the output, determine the appropriate function to use
A <- c(1,2,3)
B <- c(4,5,6)

rbind(A, B)

# Create a 3 x 3 matrix consisting of the numbers 1-9. Create this matrix using the shortcut 1:9 and by specifying the nrow argument in the matrix() function call. Assign this matrix to the variable *ma
mat <- matrix(c(1:9), nrow = 3)
mat

# Confirm that mat is a matrix
is.matrix(mat)

# Create a 5 x 5 matrix consisting of the numbers 1-25 and assign it to the variable mat2. The top row should be the numbers 1-5
mat2 <- matrix(1:25, byrow = TRUE, nrow = 5)
mat2

# Use index notation to grab a subsection of mat2 that replicates the output
mat2[2:3, 2:3]

# Use index notation to grab a subsection of mat2 that replicates the output
mat2[4:5, 4:5]

# What is the sum of all of the elements of mat2?
sum(mat2)

# Find out how to use the Built-in R Function runif() to create a 4 x 5 matrix consisting of 20 random numbers
matrix(runif(20), nrow = 4, ncol = 5)

[,1] [,2] [,3]
A 1    2    3   
B 4    5    6

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

[1] TRUE

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15  
[4,] 16   17   18   19   20  
[5,] 21   22   23   24   25

[,1] [,2]
[1,]  7    8  
[2,] 12   13

[,1] [,2]
[1,] 19   20  
[2,] 24   25

[1] 325

[,1]      [,2]      [,3]       [,4]      [,5]     
[1,] 0.9639205 0.1138385 0.56068652 0.6811618 0.1827719
[2,] 0.5913060 0.3733321 0.56804556 0.7647576 0.8904793
[3,] 0.7001121 0.9270386 0.74613455 0.4228554 0.3238529
[4,] 0.0171701 0.9086679 0.02908432 0.1759413 0.1728954